--- # tasks file for proxmoxkvm_stage

- name: Proxmox VM Automation 
  proxmox_kvm:
    api_user    : "{{ item.api_user | default('root@pam') }}"
    api_password: "{{ item.password | default('vault_rootpasswd') }}"
    api_host    : "{{ item.api_host | default('10.10.0.11') }}"
    name        : "{{ item.name | default('') }}"
    node        : "{{ item.node | default('stillwaiting') }}"
    cores       : "{{ item.cores | default('1') }}"
    vcpus       : "{{ item.vcpus | default('2') }}"
  with_items:
    "{{ proxmox_vms }}"
  register: debug_vm
- debug:
    msg: "{{ debug_vm }}"

...
