---
galaxy_info:
  role_name: repositories
  author: arillso
  description: 'Manages Repository under CentOS and Ubuntu'
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Ubuntu
      versions:
        - bionic
        - cosmic

  galaxy_tags:
    - repositories
    - repository
    - apt
    - yum
    - epel

dependencies: []
