---
# tasks file for windows_stage
- name: Disable Firewall
  win_firewall:
    state: disabled
    profiles:
    - Domain
    - Public
    - Private
  tags: disable_firewall
- name: Check for xRemoteDesktopAdmin Powershell module
  win_psmodule:
    name: xRemoteDesktopAdmin
    state: present
- name: Enable Windows Remote Desktop
  win_dsc:
    resource_name: xRemoteDesktopAdmin
    Ensure: present
    UserAuthentication: Secure
- name: Power plan to High Performance
  win_power_plan:
    name: High Performance
- name: Ensure user ansible is present
  win_user:
    name: ansible
    password: "{{ vault_ansible }}"
    state: present
    groups:
      - Users
  no_log: true
