--- # changeip.yml

- hosts: boipl
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: install needed network manager libs
      package:
        name:
        - NetworkManager
        - NetworkManager-libnm
        - nm-connection-editor
        - python3-libsemanage
        - python3-policycoreutils
        state: present
    - name: modify hosntame
      hostname:
        name: boipl01-graylog 
    - name:  configure IP
      nmcli:
        conn_name: "ens18"
        ifname: ens18
        type: ethernet
        autoconnect: yes
        gw4: 10.10.0.1
        dns4:
        - 10.10.0.80
        ip4: 10.10.0.84 
        state: present 

...
