---

- name: Windows Update
  hosts: windows_all
  gather_facts: false
  vars_files:
    ~/src/ansible-linux/vault
  vars:
    ansible_connection: winrm
    ansible_user: Administrator
    ansible_password: "{{ vault_rootpasswd }}"
    ansible_winrm_server_cert_validation: ignore
  tasks:
  - name: Install Windows Updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - DefinitionUpdates
        - Updates
      log_path: C:\ansible_wu.txt
    register: update_result
  - name: List missing updates
    debug: var=update_result
  - win_reboot:
      reboot_timeout: 3600
    when: update_result.reboot_required

...
